[package]
name = "toml-schema"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
convert_case = "0.6.0"
paste = "1.0.15"
proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = { version = "2.0.89", features = ["full"] }
try_as = "0.1.0"

[lib]
proc-macro = true
